# coding: utf-8

"""
Auto generated from openapi-generator-cli tool
"""

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api import util


class LoginSuccessResp(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, token=None):  # noqa: E501
        """LoginSuccessResp - a model defined in OpenAPI

        :param token: The token of this LoginSuccessResp.  # noqa: E501
        :type token: str
        """
        self.openapi_types = {
            'token': str
        }

        self.attribute_map = {
            'token': 'token'
        }

        self._token = token

    @classmethod
    def from_dict(cls, dikt) -> 'LoginSuccessResp':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginSuccessResp of this LoginSuccessResp.  # noqa: E501
        :rtype: LoginSuccessResp
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self):
        """Gets the token of this LoginSuccessResp.


        :return: The token of this LoginSuccessResp.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this LoginSuccessResp.


        :param token: The token of this LoginSuccessResp.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token
