# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api import util


class LoginSuccess2faResp(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None):  # noqa: E501
        """LoginSuccess2faResp - a model defined in OpenAPI

        :param message: The message of this LoginSuccess2faResp.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'message': str
        }

        self.attribute_map = {
            'message': 'message'
        }

        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'LoginSuccess2faResp':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginSuccess2faResp of this LoginSuccess2faResp.  # noqa: E501
        :rtype: LoginSuccess2faResp
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self):
        """Gets the message of this LoginSuccess2faResp.


        :return: The message of this LoginSuccess2faResp.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this LoginSuccess2faResp.


        :param message: The message of this LoginSuccess2faResp.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
